language: node_js

node_js: node

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  yarn: true

script:
  - yarn build

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: public
  skip_cleanup: true
  target-branch: master
  on:
    branch: develop
